- hosts: all
  remote_user: vagrant
  connection: ssh
  sudo: no
  vars:
    rbenv:
      env: user
      version: v0.4.0
      ruby_version: 2.2.0
    rbenv_users:
      - vagrant
    app_repogitory_url: https://github.com/yuemori/ShogiServer
  roles:
    - common
    - rbenv
    - mysql
    - shogi
  tasks:
    - name: iptables stop
      service: name=iptables state=stopped enabled=no
      sudo: true
