- hosts: all
  remote_user: vagrant
  connection: ssh
  sudo: no
  vars:
    rbenv:
      env: user
      version: v0.4.0
      ruby_version: 2.2.0
    rbenv_users:
      - vagrant
  roles:
    - common
    - rbenv
    - mysql
    - shogi
