- name: install dependencies
  yum: name={{ item }} state=installed
  with_items:
    - sqlite-devel
    - gcc-c++
  sudo: true
  tags:
    - shogi

- name: clone app repogitory
  git: repo={{ app_repogitory_url }} dest={{ app_deploy_path }} update=no
  sudo: true
  sudo_user: "{{ app_deploy_user }}"
  register: repo_clone
  tags:
    - shogi

- name: bundle installed
  shell: $SHELL -lc "bundle install"
  sudo: true
  sudo_user: "{{ app_deploy_user }}"
  args:
    chdir: "{{ app_root }}"
  when: repo_clone | changed
  tags:
    - shogi

- name: database create
  shell: $SHELL -lc "bundle exec rake db:create"
  sudo: true
  sudo_user: "{{ app_deploy_user }}"
  args:
    chdir: "{{ app_root }}"
  when: repo_clone | changed
  tags:
    - shogi

- name: database setup
  shell: $SHELL -lc "bundle exec rake db:migrate"
  sudo: true
  sudo_user: "{{ app_deploy_user }}"
  args:
    chdir: "{{ app_root }}"
  when: repo_clone | changed
  tags:
    - shogi

- name: inject seeds
  shell: $SHELL -lc "bundle exec rake db:seed_fu"
  sudo: true
  sudo_user: "{{ app_deploy_user }}"
  args:
    chdir: "{{ app_root }}"
  when: repo_clone | changed
  tags:
    - shogi

- name: set init.d script
  template: src=shogi-server dest=/etc/init.d mode=0744
  sudo: true
  tags:
    - shogi

- name: ensure {{ app_name }} started and enabled
  service: name={{ app_name }} state=started enabled=yes
  sudo: true
  tags:
    - shogi
