---
- name: check ruby {{ ruby_version }} installed
  shell: rbenv versions | grep {{ ruby_version }}
  register: ruby_installed
  ignore_errors: yes
  changed_when: false

- name: install ruby {{ ruby_version }}
  shell: rbenv install {{ ruby_version }}
  when: ruby_installed|failed

- name: set global ruby {{ ruby_version }}
  shell: rbenv global {{ ruby_version }}
  when: ruby_installed|failed

- name: rehash
  shell: rbenv rehash
  when: ruby_installed|failed

- name: check bundler installed
  shell: bundler --version
  register: bundler_installed
  ignore_errors: yes
  always_run: yes
  changed_when: false

- name: install bundler
  shell: gem install bundler
  when: bundler_installed|failed

- name: rehash
  shell: rbenv rehash
  when: ruby_installed|failed

- name: assert | register ruby version
  shell: ruby --version
  register: installed_ruby_version
  ignore_errors: yes
  always_run: yes
  changed_when: false

- name: assert | check ruby version
  assert:
    that:
      - installed_ruby_version.stdout.find(ruby_version) != -1

- name: assert | register ruby path
  shell: which ruby
  register: installed_ruby_path
  ignore_errors: yes
  always_run: yes
  changed_when: false

- name: assert | check ruby path
  assert:
    that:
      - installed_ruby_path.stdout.find(".rbenv/shims/ruby") != -1


