---
- name: install build depends
  yum: name={{ item }} state=installed
  with_items:
    - gcc-c++
    - glibc-headers
    - libyaml-devel
    - openssl-devel
    - readline-devel
    - zlib
    - zlib-devel
    - git
    - libselinux-python
  sudo: yes

- name: clone from github
  git: repo=git://github.com/sstephenson/rbenv.git dest=~/.rbenv accept_hostkey=yes

- name: add rbenv initialization to profile
  template: src=../templates/rbenv.sh.j2 dest=/etc/profile.d/rbenv.sh owner=root group=root mode=0644
  sudo: yes

- name: clone ruby-build repo
  git: repo=git://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build
